#draw_bold_text_with_bright_colors = true
import = [ "~/.config/alacritty/themes/catppuccin_mocha.toml" ]

[colors]
    [colors.primary]
        background = "#1a1d21" # base

[window]
opacity = 0.7
title = "Alacritty"

[window.padding]
x = 6
y = 6

[font]
size = 11.0

  [font.normal]
  family = "iosevka nerd font"
  style = "Regular"

  [font.bold]
  family = "iosevka nerd font"
  style = "Bold"

  [font.italic]
  family = "iosevka nerd font"
  style = "Italic"

  [font.bold_italic]
  family = "iosevka nerd font"
  style = "Bold Italic"

  [font.offset]
  x = 0
  y = 1

